[package]
name = "bingwallpaper"
version = "1.0.1"
edition = "2021"

authors = ["Thibault Meyer"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/thibaultmeyer/bingwallpaper"
repository = "https://github.com/thibaultmeyer/bingwallpaper"
keywords = ["bing-wallpaper", "wallpaper", "wallpaper-changer", "bing-wallpaper-api"]

include = ["/src", "LICENSE"]
publish = false


[dependencies]
chrono = "0.4.26"
clap = { version = "4.3.19", features = ["derive"] }
confy = "0.5.1"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = "1.0.174"
serde_derive = "1.0.174"
winit = "0.28.6"


[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["wincon", "winuser"] }
